corners:
- - 0.06499999999999999
  - 0.08349999999999998
  - -2.7755575615628914e-17
- - -0.065
  - 0.08349999999999999
  - -2.7755575615628914e-17
- - -0.06500000000000002
  - -0.08350000000000003
  - -8.326672684688674e-17
- - 0.065
  - -0.0835
  - -5.551115123125783e-17
- - -1.734723475976807e-18
  - -2.7755575615628914e-17
  - -2.7755575615628914e-17
extristric:
- - 0.003665818395723554
  - 0.029702310958813868
  - 0.22313262152229177
- - 0.9986550413835654
  - 0.006223083633283514
  - 0.051472143430033125
- - 0.030515006061173293
  - -0.8731579982254193
  - -0.48648118621388153
- - 0.041915900613911435
  - 0.487397561919499
  - -0.8721735342869863
plane:
- -0.005640366114675999
- -0.4103914201259613
- -0.9118919968605042
- 0.20515288412570953
white_area_pose_cam:
- - 0.9987276493457357
  - -0.0064535927153376305
  - -0.05000043882115104
  - 0.0036637034381768615
- - 0.029972451906561327
  - 0.8734756708811281
  - 0.48594237515073974
  - 0.029706564395770373
- - 0.040538019679145554
  - -0.4868233184077229
  - 0.8725578123690031
  - 0.22312648535043844
- - 0.0
  - 0.0
  - 0.0
  - 1.0
white_area_pose_world:
- - 1.0
  - 0.0
  - 0.0
  - 0.1488605726149887
- - 0.0
  - 1.0
  - 0.0
  - -0.005009569663687256
- - 0.0
  - 0.0
  - 1.0
  - -0.03682965973666055
- - 0.0
  - 0.0
  - 0.0
  - 1.0
