SM:
  - 1.0028031510189706
  - -0.010830151037929881
  - 0.0077619905993511094
  - -0.0020018341537684664
  - 1.0047183790398
  - -0.033887502736003286
  - -0.018301298826314882
  - -0.0083152923070039381
  - 1.0035178387064076
bias:
  - 0.050491000153353602
  - 0.20053641531097049
  - -0.097536626022432044