controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 30.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3

    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] 
    
    # 1. 声明控制器别名，保持 "FollowPath" 不变
    controller_plugins: ["FollowPath"]

    # 2. 将 "FollowPath" 的插件类型指向 RotationShimController
    controller_plugin_types: ["nav2_rotation_shim_controller::RotationShimController"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    # Goal checker parameters
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      
    # 3. 重新配置 "FollowPath" 块
    FollowPath:
      # 3.1 指定 FollowPath 插件本身是 RotationShimController
      plugin: "nav2_rotation_shim_controller::RotationShimController"

      # 3.2  RotationShimController 的参数，用于控制预旋转
      angular_dist_threshold: 0.5     # 当与路径方向差值 > 0.5 rad 时先旋转
      forward_sampling_distance: 0.4  # 用前 0.3m 路径方向作为目标朝向
      rotate_to_heading_angular_vel: 2.5  # 执行预旋转时的角速度
      max_rotational_vel: 3.0          # ← 新增，务必 ≥ 上行
      max_angular_accel: 5.0
      simulate_ahead_time: 1.0

      # 3.3 指定主控制器为 DWB
      primary_controller: "dwb_core::DWBLocalPlanner"

      # 3.4 所有 DWB 的参数原封不动地放在这里
      # DWB parameters start here
      debug_trajectory_details: True
      min_vel_x: 0.0   #-0.4
      min_vel_y: 0.0
      max_vel_x: 0.4
      max_vel_y: 0.0
      max_vel_theta: 3.0
      min_speed_xy: 0.0
      max_speed_xy: 0.4
      min_speed_theta: 0.0
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 5.0
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -5.0
      vx_samples: 20
      vy_samples: 1
      vtheta_samples: 30
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
      # DWB parameters end here


controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False